### ISSUE TITLE
Remove .ready behavior for something smarter

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/contracts#12]
Ref discussion at https://github.com/polyswarm/contracts/commit/d3751cba9d3c6adfec67f1cf9722232d65d33508

syncing containers over volumes is going to be a problem and currently has some disadvantages. one possible solution is hosting contracts + config over http etc from contracts container. we had some back and forth about how to coordinate things when first setting up the compose file in `orchestration`, would like to track thoughts about how everything should be fitting together.

**Comment by ceseale** [comment]
Planning to store configs from contracts in `consul` via these PRs (https://github.com/polyswarm/contracts/pull/28, https://github.com/polyswarm/orchestration/pull/21, https://github.com/polyswarm/polyswarmd/pull/47). 

Tasks:

- [ ]  update to idempotent flag to work with `consul`
- [ ] remove`polyswarmd.tar` logic since configs can be grabbed from `consul`

**Comment by ceseale** [comment]
Closed with https://github.com/polyswarm/polyswarmd/pull/47, https://github.com/polyswarm/contracts/pull/28, https://github.com/polyswarm/orchestration/pull/21
