### ISSUE TITLE
create_config.js fails to error out when it misses steps.

### ISSUE THREAD

**Issue by scsich** [polyswarm/contracts#29]
**Describe the bug**
If home or side chain has a comms problem, `create_config.js` happily continues without error and silently doesn't produce a config.

**To Reproduce**
0. Spin up a test environment where sidechain isn't available.
1. `truffle exec scripts/create_config.js --home=$HOME_CHAIN --side=$SIDE_CHAIN --ipfs=$IPFS --options=$OPTIONS`
2. echo $? == 0

**Expected behavior**
Produce a return code of non-zero and exit if you're unable to complete *any* critical step:
* Homechain deploy
* Sidechain deploy
* Config production

**Comment by myhndl** [comment]
This was discussed in Slack last week. @ceseale what's the status on this one?

It looks like we have various `try` / `catch` blocks, but they don't cover 100% of this script. I think a safer solution is to default to failure (invert the `try` / `catch` paradigm). Perhaps we have a `state` variable we advance in lockstep with successful actions.

E.g.:
1. `state` == `begin`
...
1. `state` == `putABI`
1. `state` == `putConfig` - only advanced to this `state` if `state` is currently `putABI`. Else, exit with failure.
...
1. `state` == `success`

... and such.

Then the end of the script, always return 1 (fail) unless `state` has reached the final state (`success`). This way we don't have to worry about missing failure outside of `try` / `catch` blocks.

**Comment by ceseale** [comment]
@myhndl yeah I talked to @Rizato and we agreed that the way I had`try` / `catch` blocks setup wouldn't be sufficient. The issue was the way we were using the callback from `truffle`. I've been doing some testing and it seems to be exiting correctly. I think the issue can be close with https://github.com/polyswarm/contracts/pull/34

It's not useful to track the `state` of the script in the way you're suggesting because it will still exit with `0` if there is an exception that isn't caught due to the way `truffle exec` works.
